spring:
  application.name: spring-ai
  ai:
    ollama:
      embedding:
        model: bge-m3
      chat:
        model: llama3.1:8b
#        model: qwen2.5-coder:14b
#    gigachat:
#      auth:
#        bearer:
#          api-key: ${GIGACHAT_API_KEY}
#        scope: gigachat_api_pers
#        certs:
#          ca-certs: ${GIGACHAT_CA_CERT}
#      chat:
#        temperature: 0.0